name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['25', '26', '27', '28']
    container:
      image: erlang:${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v5
      - run: rebar3 compile
      - run: rebar3 ct
      - run: rebar3 xref
      - run: rebar3 dialyzer

  macos:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        otp: ['27', '28']
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
      - run: rebar3 compile
      - run: rebar3 ct
      - run: rebar3 xref
      - run: rebar3 dialyzer
